version: "3"

services:
  jekyll:
    container_name: "gis.utah.gov"
    image: "jekyll/jekyll:4"
    command: "jekyll serve --watch --livereload"
    environment:
      - JEKYLL_ENV=production
      - NODE_ENV=production
    volumes:
      - "./:/srv/jekyll"
    ports:
      - "4000:4000"
      - "35729:35729"
