version: "3"

services:
  jekyll:
    container_name: "gis.utah.gov"
    image: "jekyll/jekyll:4"
    command: "jekyll serve --livereload --drafts --future --port 5000 --livereload_port 35729"
    environment:
      - JEKYLL_ENV=docker
    volumes:
      - "./:/srv/jekyll"
    ports:
      - "5000:5000"
      - "35729:35729"
