version: "2"

services:
  jekyll:
    container_name: "gis.utah.gov"
    image: "jekyll/jekyll"
    command: "jekyll serve --watch --incremental"
    volumes:
      - "./:/srv/jekyll"
    ports:
      - "127.0.0.1:4000:4000"
      - "127.0.0.1:35729:35729"

